const District = require("../../models/district.model");
const DistrictDao = require("../../dao/district.dao");
const CityDao = require("../../dao/city.dao");

const districts = [
    { cityName: "An Giang", districtName:"An Phú"},
    { cityName: "An Giang", districtName:"Châu Đốc" },
    { cityName: "An Giang", districtName:"Châu Phú" },
    { cityName: "An Giang", districtName:"Châu Thành" },
    { cityName: "An Giang", districtName:"Chợ Mới" },
    { cityName: "An Giang", districtName:"Long Xuyên" },
    { cityName: "An Giang", districtName:"Phú Tân" },
    { cityName: "An Giang", districtName:"Tân Châu" },
    { cityName: "An Giang", districtName:"Thoại Sơn" },
    { cityName: "An Giang", districtName:"Tịnh Biên" },
    { cityName: "An Giang", districtName:"Tri Tôn" },
    { cityName: "Bà Rịa - Vũng Tàu", districtName:"Bà Rịa" },
    { cityName: "Bà Rịa - Vũng Tàu", districtName:"Châu Đức" },
    { cityName: "Bà Rịa - Vũng Tàu", districtName:"Côn Đảo" },
    { cityName: "Bà Rịa - Vũng Tàu", districtName:"Đất Đỏ" },
    { cityName: "Bà Rịa - Vũng Tàu", districtName:"Long Điền" },
    { cityName: "Bà Rịa - Vũng Tàu", districtName:"Phú Mỹ" },
    { cityName: "Bà Rịa - Vũng Tàu", districtName:"Vũng Tàu" },
    { cityName: "Bà Rịa - Vũng Tàu", districtName:"Xuyên Mộc" },
    { cityName: "Bắc Giang", districtName:"Bắc Giang" },
    { cityName: "Bắc Giang", districtName:"Hiệp Hòa" },
    { cityName: "Bắc Giang", districtName:"Lạng Giang" },
    { cityName: "Bắc Giang", districtName:"Lục Nam" },
    { cityName: "Bắc Giang", districtName:"Lục Ngạn" },
    { cityName: "Bắc Giang", districtName:"Sơn Động" },
    { cityName: "Bắc Giang", districtName:"Tân Yên" },
    { cityName: "Bắc Giang", districtName:"Việt Yên" },
    { cityName: "Bắc Giang", districtName:"Yên Dũng" },
    { cityName: "Bắc Giang", districtName:"Yên Thế" },
    { cityName: "Bắc Kạn", districtName:"Ba Bể" },
    { cityName: "Bắc Kạn", districtName:"Bắc Kạn" },
    { cityName: "Bắc Kạn", districtName:"Bạch Thông" },
    { cityName: "Bắc Kạn", districtName:"Chợ Đồn" },
    { cityName: "Bắc Kạn", districtName:"Chợ Mới" },
    { cityName: "Bắc Kạn", districtName:"Na Rì" },
    { cityName: "Bắc Kạn", districtName:"Ngân Sơn" },
    { cityName: "Bắc Kạn", districtName:"Pác Nặm" },
    { cityName: "Bạc Liêu", districtName:"Bạc Liêu" },
    { cityName: "Bạc Liêu", districtName:"Đông Hải" },
    { cityName: "Bạc Liêu", districtName:"Giá Rai" },
    { cityName: "Bạc Liêu", districtName:"Hòa Bình" },
    { cityName: "Bạc Liêu", districtName:"Hồng Dân" },
    { cityName: "Bạc Liêu", districtName:"Phước Long" },
    { cityName: "Bạc Liêu", districtName:"Vĩnh Lợi" },
    { cityName: "Bắc Ninh", districtName:"Bắc Ninh" },
    { cityName: "Bắc Ninh", districtName:"Gia Bình" },
    { cityName: "Bắc Ninh", districtName:"Lương Tài" },
    { cityName: "Bắc Ninh", districtName:"Quế Võ" },
    { cityName: "Bắc Ninh", districtName:"Thuận Thành" },
    { cityName: "Bắc Ninh", districtName:"Tiên Du" },
    { cityName: "Bắc Ninh", districtName:"Từ Sơn" },
    { cityName: "Bắc Ninh", districtName:"Yên Phong" },
    { cityName: "Bến Tre", districtName:"Ba Tri" },
    { cityName: "Bến Tre", districtName:"Bến Tre" },
    { cityName: "Bến Tre", districtName:"Bình Đại" },
    { cityName: "Bến Tre", districtName:"Châu Thành" },
    { cityName: "Bến Tre", districtName:"Chợ Lách" },
    { cityName: "Bến Tre", districtName:"Giồng Trôm" },
    { cityName: "Bến Tre", districtName:"Mỏ Cày Bắc" },
    { cityName: "Bến Tre", districtName:"Mỏ Cày Nam" },
    { cityName: "Bến Tre", districtName:"Thạnh Phú" },
    { cityName: "Bình Định", districtName:"An Lão" },
    { cityName: "Bình Định", districtName:"An Nhơn" },
    { cityName: "Bình Định", districtName:"Hoài Ân" },
    { cityName: "Bình Định", districtName:"Hoài Nhơn" },
    { cityName: "Bình Định", districtName:"Phù Cát" },
    { cityName: "Bình Định", districtName:"Phù Mỹ" },
    { cityName: "Bình Định", districtName:"Quy Nhơn" },
    { cityName: "Bình Định", districtName:"Tây Sơn" },
    { cityName: "Bình Định", districtName:"Tuy Phước" },
    { cityName: "Bình Định", districtName:"Vân Canh" },
    { cityName: "Bình Định", districtName:"Vĩnh Thạnh" },
    { cityName: "Bình Dương", districtName:"Bắc Tân Uyên" },
    { cityName: "Bình Dương", districtName:"Bàu Bàng" },
    { cityName: "Bình Dương", districtName:"Bến Cát" },
    { cityName: "Bình Dương", districtName:"Dầu Tiếng" },
    { cityName: "Bình Dương", districtName:"Dĩ An" },
    { cityName: "Bình Dương", districtName:"Phú Giáo" },
    { cityName: "Bình Dương", districtName:"Phú Giáo" },
    { cityName: "Bình Dương", districtName:"Tân Uyên" },
    { cityName: "Bình Dương", districtName:"Thủ Dầu Một" },
    { cityName: "Bình Dương", districtName:"Thuận An" },
    { cityName: "Bình Phước", districtName:"Bình Long" },
    { cityName: "Bình Phước", districtName:"Bù Đăng" },
    { cityName: "Bình Phước", districtName:"Bù Đốp" },
    { cityName: "Bình Phước", districtName:"Bù Gia Mập" },
    { cityName: "Bình Phước", districtName:"Chơn Thành" },
    { cityName: "Bình Phước", districtName:"Đồng Phú" },
    { cityName: "Bình Phước", districtName:"Đồng Xoài" },
    { cityName: "Bình Phước", districtName:"Hớn Quản" },
    { cityName: "Bình Phước", districtName:"Lộc Ninh" },
    { cityName: "Bình Phước", districtName:"Phú Riềng" },
    { cityName: "Bình Phước", districtName:"Phước Long" },
    { cityName: "Bình Thuận", districtName:"Bắc Bình" },
    { cityName: "Bình Thuận", districtName:"đảo Phú Quý" },
    { cityName: "Bình Thuận", districtName:"Đức Linh" },
    { cityName: "Bình Thuận", districtName:"Hàm Tân" },
    { cityName: "Bình Thuận", districtName:"Hàm Thuận Bắc" },
    { cityName: "Bình Thuận", districtName:"Hàm Thuận Nam" },
    { cityName: "Bình Thuận", districtName:"La Gi" },
    { cityName: "Bình Thuận", districtName:"Phan Thiết" },
    { cityName: "Bình Thuận", districtName:"Tánh Linh" },
    { cityName: "Bình Thuận", districtName:"Tuy Phong" },
    { cityName: "Cà Mau", districtName:"Cà Mau" },
    { cityName: "Cà Mau", districtName:"Cái Nước" },
    { cityName: "Cà Mau", districtName:"Đầm Dơi" },
    { cityName: "Cà Mau", districtName:"Năm Căn" },
    { cityName: "Cà Mau", districtName:"Ngọc Hiển" },
    { cityName: "Cà Mau", districtName:"Phú Tân" },
    { cityName: "Cà Mau", districtName:"Thới Bình" },
    { cityName: "Cà Mau", districtName:"Trần Văn Thời" },
    { cityName: "Cà Mau", districtName:"U Minh" },
    { cityName: "Cần Thơ", districtName:"Bình Thủy" },
    { cityName: "Cần Thơ", districtName:"Cái Răng" },
    { cityName: "Cần Thơ", districtName:"Cờ Đỏ" },
    { cityName: "Cần Thơ", districtName:"Ninh Kiều" },
    { cityName: "Cần Thơ", districtName:"Ô Môn" },
    { cityName: "Cần Thơ", districtName:"Phong Điền" },
    { cityName: "Cần Thơ", districtName:"Thới Lai" },
    { cityName: "Cần Thơ", districtName:"Thốt Nốt" },
    { cityName: "Cần Thơ", districtName:"Vĩnh Thạnh" },
    { cityName: "Cao Bằng", districtName:"Bảo Lạc" },
    { cityName: "Cao Bằng", districtName:"Bảo Lâm" },
    { cityName: "Cao Bằng", districtName:"Cao Bằng" },
    { cityName: "Cao Bằng", districtName:"Hạ Lang" },
    { cityName: "Cao Bằng", districtName:"Hà Quảng" },
    { cityName: "Cao Bằng", districtName:"Hòa An" },
    { cityName: "Cao Bằng", districtName:"Hòa An" },
    { cityName: "Cao Bằng", districtName:"Nguyên Bình" },
    { cityName: "Cao Bằng", districtName:"Phục Hòa" },
    { cityName: "Cao Bằng", districtName:"Quảng Uyên" },
    { cityName: "Cao Bằng", districtName:"Thạch An" },
    { cityName: "Cao Bằng", districtName:"Thông Nông" },
    { cityName: "Cao Bằng", districtName:"Trà Lĩnh" },
    { cityName: "Cao Bằng", districtName:"Trùng Khánh" },
    { cityName: "Đà Nẵng", districtName:"Cẩm Lệ" },
    { cityName: "Đà Nẵng", districtName:"Hải Châu" },
    { cityName: "Đà Nẵng", districtName:"Hòa Vang" },
    { cityName: "Đà Nẵng", districtName:"Hoàng Sa" },
    { cityName: "Đà Nẵng", districtName:"Liên Chiểu" },
    { cityName: "Đà Nẵng", districtName:"Ngũ Hành Sơn" },
    { cityName: "Đà Nẵng", districtName:"Sơn Trà" },
    { cityName: "Đà Nẵng", districtName:"Thanh Khê" },
    { cityName: "Đắk Lắk", districtName:"Buôn Đôn" },
    { cityName: "Đắk Lắk", districtName:"Buôn Hồ" },
    { cityName: "Đắk Lắk", districtName:"Buôn Ma Thuột" },
    { cityName: "Đắk Lắk", districtName:"Cư Kuin" },
    { cityName: "Đắk Lắk", districtName:"Cư M'gar" },
    { cityName: "Đắk Lắk", districtName:"Ea H'Leo" },
    { cityName: "Đắk Lắk", districtName:"Ea Kar" },
    { cityName: "Đắk Lắk", districtName:"Ea Súp" },
    { cityName: "Đắk Lắk", districtName:"Krông Ana" },
    { cityName: "Đắk Lắk", districtName:"Krông Bông" },
    { cityName: "Đắk Lắk", districtName:"Krông Buk" },
    { cityName: "Đắk Lắk", districtName:"Krông Năng" },
    { cityName: "Đắk Lắk", districtName:"Krông Pắc" },
    { cityName: "Đắk Lắk", districtName:"Lắk" },
    { cityName: "Đắk Lắk", districtName:"M'Đrắk" },
    { cityName: "Đắk Nông", districtName:"Cư Jút" },
    { cityName: "Đắk Nông", districtName:"Đăk GLong" },
    { cityName: "Đắk Nông", districtName:"Đăk Mil" },
    { cityName: "Đắk Nông", districtName:"Đăk R'Lấp" },
    { cityName: "Đắk Nông", districtName:"Đăk Song" },
    { cityName: "Đắk Nông", districtName:"Gia Nghĩa" },
    { cityName: "Đắk Nông", districtName:"Krông Nô" },
    { cityName: "Đắk Nông", districtName:"Tuy Đức" },
    { cityName: "Điện Biên", districtName:"Điện Biên" },
    { cityName: "Điện Biên", districtName:"Điện Biên Đông" },
    { cityName: "Điện Biên", districtName:"Điện Biên Phủ" },
    { cityName: "Điện Biên", districtName:"Mường ảng" },
    { cityName: "Điện Biên", districtName:"Mường Chà" },
    { cityName: "Điện Biên", districtName:"Mường Lay" },
    { cityName: "Điện Biên", districtName:"Mường Nhé" },
    { cityName: "Điện Biên", districtName:"Nậm Pồ" },
    { cityName: "Điện Biên", districtName:"Tủa Chùa" },
    { cityName: "Điện Biên", districtName:"Tuần Giáo" },
    { cityName: "Đồng Nai", districtName:"Biên Hòa" },
    { cityName: "Đồng Nai", districtName:"Cẩm Mỹ" },
    { cityName: "Đồng Nai", districtName:"Định Quán" },
    { cityName: "Đồng Nai", districtName:"Long Khánh" },
    { cityName: "Đồng Nai", districtName:"Long Thành" },
    { cityName: "Đồng Nai", districtName:"Nhơn Trạch" },
    { cityName: "Đồng Nai", districtName:"Tân Phú" },
    { cityName: "Đồng Nai", districtName:"Thống Nhất" },
    { cityName: "Đồng Nai", districtName:"Trảng Bom" },
    { cityName: "Đồng Nai", districtName:"Vĩnh Cửu" },
    { cityName: "Đồng Nai", districtName:"Xuân Lộc" },
    { cityName: "Đồng Tháp", districtName:"Cao Lãnh" },
    { cityName: "Đồng Tháp", districtName:"Cao Lãnh" },
    { cityName: "Đồng Tháp", districtName:"Châu Thành" },
    { cityName: "Đồng Tháp", districtName:"Hồng Ngự" },
    { cityName: "Đồng Tháp", districtName:"Hồng Ngự" },
    { cityName: "Đồng Tháp", districtName:"Lai Vung" },
    { cityName: "Đồng Tháp", districtName:"Lấp Vò" },
    { cityName: "Đồng Tháp", districtName:"Sa Đéc" },
    { cityName: "Đồng Tháp", districtName:"Tam Nông" },
    { cityName: "Đồng Tháp", districtName:"Tân Hồng" },
    { cityName: "Đồng Tháp", districtName:"Thanh Bình" },
    { cityName: "Đồng Tháp", districtName:"Tháp Mười" },
    { cityName: "Gia Lai", districtName:"An Khê" },
    { cityName: "Gia Lai", districtName:"Ayun Pa" },
    { cityName: "Gia Lai", districtName:"Chư Păh" },
    { cityName: "Gia Lai", districtName:"Chư Prông" },
    { cityName: "Gia Lai", districtName:"Chư Pưh" },
    { cityName: "Gia Lai", districtName:"Chư Sê" },
    { cityName: "Gia Lai", districtName:"Đak Đoa" },
    { cityName: "Gia Lai", districtName:"Đak Pơ" },
    { cityName: "Gia Lai", districtName:"Đức Cơ" },
    { cityName: "Gia Lai", districtName:"Ia Grai" },
    { cityName: "Gia Lai", districtName:"Ia Pa" },
    { cityName: "Gia Lai", districtName:"KBang" },
    { cityName: "Gia Lai", districtName:"Kông Chro" },
    { cityName: "Gia Lai", districtName:"Krông Pa" },
    { cityName: "Gia Lai", districtName:"Mang Yang" },
    { cityName: "Gia Lai", districtName:"Phú Thiện" },
    { cityName: "Gia Lai", districtName:"Pleiku" },
    { cityName: "Hà Giang", districtName:"Bắc Mê" },
    { cityName: "Hà Giang", districtName:"Bắc Mê" },
    { cityName: "Hà Giang", districtName:"Bắc Quang" },
    { cityName: "Hà Giang", districtName:"Đồng Văn" },
    { cityName: "Hà Giang", districtName:"Hà Giang" },
    { cityName: "Hà Giang", districtName:"Hoàng Su Phì" },
    { cityName: "Hà Giang", districtName:"Mèo Vạc" },
    { cityName: "Hà Giang", districtName:"Quản Bạ" },
    { cityName: "Hà Giang", districtName:"Quang Bình" },
    { cityName: "Hà Giang", districtName:"Vị Xuyên" },
    { cityName: "Hà Giang", districtName:"Xín Mần" },
    { cityName: "Hà Giang", districtName:"Yên Minh" },
    { cityName: "Hà Nam", districtName:"Bình Lục" },
    { cityName: "Hà Nam", districtName:"Duy Tiên" },
    { cityName: "Hà Nam", districtName:"Kim Bảng" },
    { cityName: "Hà Nam", districtName:"Lý Nhân" },
    { cityName: "Hà Nam", districtName:"Phủ Lý" },
    { cityName: "Hà Nam", districtName:"Thanh Liêm" },
    { cityName: "Hà Nội", districtName:"Ba Đình" },
    { cityName: "Hà Nội", districtName:"Ba Vì" },
    { cityName: "Hà Nội", districtName:"Bắc Từ Liêm" },
    { cityName: "Hà Nội", districtName:"Cầu Giấy" },
    { cityName: "Hà Nội", districtName:"Chương Mỹ" },
    { cityName: "Hà Nội", districtName:"Đan Phượng" },
    { cityName: "Hà Nội", districtName:"Đông Anh" },
    { cityName: "Hà Nội", districtName:"Đống Đa" },
    { cityName: "Hà Nội", districtName:"Gia Lâm" },
    { cityName: "Hà Nội", districtName:"Hà Đông" },
    { cityName: "Hà Nội", districtName:"Hai Bà Trưng" },
    { cityName: "Hà Nội", districtName:"Hoài Đức" },
    { cityName: "Hà Nội", districtName:"Hoàn Kiếm" },
    { cityName: "Hà Nội", districtName:"Hoàng Mai" },
    { cityName: "Hà Nội", districtName:"Long Biên" },
    { cityName: "Hà Nội", districtName:"Mê Linh" },
    { cityName: "Hà Nội", districtName:"Mỹ Đức" },
    { cityName: "Hà Nội", districtName:"Nam Từ Liêm" },
    { cityName: "Hà Nội", districtName:"Phú Xuyên" },
    { cityName: "Hà Nội", districtName:"Phúc Thọ" },
    { cityName: "Hà Nội", districtName:"Quốc Oai" },
    { cityName: "Hà Nội", districtName:"Sóc Sơn" },
    { cityName: "Hà Nội", districtName:"Sơn Tây" },
    { cityName: "Hà Nội", districtName:"Tây Hồ" },
    { cityName: "Hà Nội", districtName:"Thạch Thất" },
    { cityName: "Hà Nội", districtName:"Thanh Oai" },
    { cityName: "Hà Nội", districtName:"Thanh Trì" },
    { cityName: "Hà Nội", districtName:"Thanh Xuân" },
    { cityName: "Hà Nội", districtName:"Thường Tín" },
    { cityName: "Hà Nội", districtName:"Ứng Hòa" },
    { cityName: "Hà Tĩnh", districtName:"Cẩm Xuyên" },
    { cityName: "Hà Tĩnh", districtName:"Can Lộc" },
    { cityName: "Hà Tĩnh", districtName:"Đức Thọ" },
    { cityName: "Hà Tĩnh", districtName:"Hà Tĩnh" },
    { cityName: "Hà Tĩnh", districtName:"Hồng Lĩnh" },
    { cityName: "Hà Tĩnh", districtName:"Hương Khê" },
    { cityName: "Hà Tĩnh", districtName:"Hương Sơn" },
    { cityName: "Hà Tĩnh", districtName:"Kỳ Anh" },
    { cityName: "Hà Tĩnh", districtName:"Kỳ Anh" },
    { cityName: "Hà Tĩnh", districtName:"Lộc Hà" },
    { cityName: "Hà Tĩnh", districtName:"Nghi Xuân" },
    { cityName: "Hà Tĩnh", districtName:"Thạch Hà" },
    { cityName: "Hà Tĩnh", districtName:"Vũ Quang" },
    { cityName: "Hải Dương", districtName:"Bình Giang" },
    { cityName: "Hải Dương", districtName:"Cẩm Giàng" },
    { cityName: "Hải Dương", districtName:"Chí Linh" },
    { cityName: "Hải Dương", districtName:"Gia Lộc" },
    { cityName: "Hải Dương", districtName:"Hải Dương" },
    { cityName: "Hải Dương", districtName:"Kim Thành" },
    { cityName: "Hải Dương", districtName:"Kinh Môn" },
    { cityName: "Hải Dương", districtName:"Nam Sách" },
    { cityName: "Hải Dương", districtName:"Ninh Giang" },
    { cityName: "Hải Dương", districtName:"Thanh Hà" },
    { cityName: "Hải Dương", districtName:"Thanh Miện" },
    { cityName: "Hải Dương", districtName:"Tứ Kỳ" },
    { cityName: "Hải Phòng", districtName:"An Dương" },
    { cityName: "Hải Phòng", districtName:"An Lão" },
    { cityName: "Hải Phòng", districtName:"Bạch Long Vĩ" },
    { cityName: "Hải Phòng", districtName:"Cát Hải" },
    { cityName: "Hải Phòng", districtName:"Đồ Sơn" },
    { cityName: "Hải Phòng", districtName:"Dương Kinh" },
    { cityName: "Hải Phòng", districtName:"Hải An" },
    { cityName: "Hải Phòng", districtName:"Hồng Bàng" },
    { cityName: "Hải Phòng", districtName:"Kiến An" },
    { cityName: "Hải Phòng", districtName:"Kiến Thụy" },
    { cityName: "Hải Phòng", districtName:"Lê Chân" },
    { cityName: "Hải Phòng", districtName:"Ngô Quyền" },
    { cityName: "Hải Phòng", districtName:"Thủy Nguyên" },
    { cityName: "Hải Phòng", districtName:"Tiên Lãng" },
    { cityName: "Hải Phòng", districtName:"Vĩnh Bảo" },
    { cityName: "Hậu Giang", districtName:"Châu Thành" },
    { cityName: "Hậu Giang", districtName:"Châu Thành A" },
    { cityName: "Hậu Giang", districtName:"Long Mỹ" },
    { cityName: "Hậu Giang", districtName:"Long Mỹ" },
    { cityName: "Hậu Giang", districtName:"Ngã Bảy" },
    { cityName: "Hậu Giang", districtName:"Phụng Hiệp" },
    { cityName: "Hậu Giang", districtName:"Vị Thanh" },
    { cityName: "Hậu Giang", districtName:"Vị Thủy" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 1" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 2" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 3" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 4" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 5" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 6" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 7" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 8" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 9" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 10" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 11" },
    { cityName: "Hồ Chí Minh", districtName:"Quận 12" },
    { cityName: "Hồ Chí Minh", districtName:"Bình Chánh" },
    { cityName: "Hồ Chí Minh", districtName:"Bình Tân" },
    { cityName: "Hồ Chí Minh", districtName:"Bình Thạnh" },
    { cityName: "Hồ Chí Minh", districtName:"Cần Giờ" },
    { cityName: "Hồ Chí Minh", districtName:"Củ Chi" },
    { cityName: "Hồ Chí Minh", districtName:"Gò Vấp" },
    { cityName: "Hồ Chí Minh", districtName:"Hóc Môn" },
    { cityName: "Hồ Chí Minh", districtName:"Nhà Bè" },
    { cityName: "Hồ Chí Minh", districtName:"Phú Nhuận" },
    { cityName: "Hồ Chí Minh", districtName:"Tân Bình" },
    { cityName: "Hồ Chí Minh", districtName:"Tân Phú" },
    { cityName: "Hồ Chí Minh", districtName:"Thủ Đức" },
    { cityName: "Hòa Bình", districtName:"Cao Phong" },
    { cityName: "Hòa Bình", districtName:"Đà Bắc" },
    { cityName: "Hòa Bình", districtName:"Hòa Bình" },
    { cityName: "Hòa Bình", districtName:"Kim Bôi" },
    { cityName: "Hòa Bình", districtName:"Kỳ Sơn" },
    { cityName: "Hòa Bình", districtName:"Lạc Sơn" },
    { cityName: "Hòa Bình", districtName:"Lạc Thủy" },
    { cityName: "Hòa Bình", districtName:"Lương Sơn" },
    { cityName: "Hòa Bình", districtName:"Mai Châu" },
    { cityName: "Hòa Bình", districtName:"Tân Lạc" },
    { cityName: "Hòa Bình", districtName:"Yên Thủy" },
    { cityName: "Hưng Yên", districtName:"Ân Thi" },
    { cityName: "Hưng Yên", districtName:"Hưng Yên" },
    { cityName: "Hưng Yên", districtName:"KHóai Châu" },
    { cityName: "Hưng Yên", districtName:"Kim Động" },
    { cityName: "Hưng Yên", districtName:"Mỹ Hào" },
    { cityName: "Hưng Yên", districtName:"Phù Cừ" },
    { cityName: "Hưng Yên", districtName:"Tiên Lữ" },
    { cityName: "Hưng Yên", districtName:"Văn Giang" },
    { cityName: "Hưng Yên", districtName:"Văn Lâm" },
    { cityName: "Hưng Yên", districtName:"Yên Mỹ" },
    { cityName: "Khánh Hòa", districtName:"Cam Lâm" },
    { cityName: "Khánh Hòa", districtName:"Cam Ranh" },
    { cityName: "Khánh Hòa", districtName:"đảo Trường Sa" },
    { cityName: "Khánh Hòa", districtName:"Diên Khánh" },
    { cityName: "Khánh Hòa", districtName:"Khánh Sơn" },
    { cityName: "Khánh Hòa", districtName:"Khánh Vĩnh" },
    { cityName: "Khánh Hòa", districtName:"Nha Trang" },
    { cityName: "Khánh Hòa", districtName:"Ninh Hòa" },
    { cityName: "Khánh Hòa", districtName:"Vạn Ninh" },
    { cityName: "Kiên Giang", districtName:"An Biên" },
    { cityName: "Kiên Giang", districtName:"An Minh" },
    { cityName: "Kiên Giang", districtName:"Châu Thành" },
    { cityName: "Kiên Giang", districtName:"Giang Thành" },
    { cityName: "Kiên Giang", districtName:"Giồng Riềng" },
    { cityName: "Kiên Giang", districtName:"Gò Quao" },
    { cityName: "Kiên Giang", districtName:"Hà Tiên" },
    { cityName: "Kiên Giang", districtName:"Hòn Đất" },
    { cityName: "Kiên Giang", districtName:"Kiên Hải" },
    { cityName: "Kiên Giang", districtName:"Kiên Lương" },
    { cityName: "Kiên Giang", districtName:"Phú Quốc" },
    { cityName: "Kiên Giang", districtName:"Rạch Giá" },
    { cityName: "Kiên Giang", districtName:"Tân Hiệp" },
    { cityName: "Kiên Giang", districtName:"U Minh Thượng" },
    { cityName: "Kiên Giang", districtName:"Vĩnh Thuận" },
    { cityName: "Kon Tum", districtName:"ĐĂK GLEI" },
    { cityName: "Kon Tum", districtName:"Đăk Hà" },
    { cityName: "Kon Tum", districtName:"Đăk Tô" },
    { cityName: "Kon Tum", districtName:"IA H'DRAI" },
    { cityName: "Kon Tum", districtName:"Kon Plông" },
    { cityName: "Kon Tum", districtName:"Kon Rẫy" },
    { cityName: "Kon Tum", districtName:"Kon Tum" },
    { cityName: "Kon Tum", districtName:"Ngọc Hồi" },
    { cityName: "Kon Tum", districtName:"Sa Thầy" },
    { cityName: "Kon Tum", districtName:"Tu Mơ Rông" },
    { cityName: "Lai Châu", districtName:"Lai Châu" },
    { cityName: "Lai Châu", districtName:"Mường Tè" },
    { cityName: "Lai Châu", districtName:"Nậm Nhùn" },
    { cityName: "Lai Châu", districtName:"Phong Thổ" },
    { cityName: "Lai Châu", districtName:"Sìn Hồ" },
    { cityName: "Lai Châu", districtName:"Tam Đường" },
    { cityName: "Lai Châu", districtName:"Tân Uyên" },
    { cityName: "Lai Châu", districtName:"Than Uyên" },
    { cityName: "Lâm Đồng", districtName:"Bảo Lâm" },
    { cityName: "Lâm Đồng", districtName:"Bảo Lộc" },
    { cityName: "Lâm Đồng", districtName:"Cát Tiên" },
    { cityName: "Lâm Đồng", districtName:"Đạ Huoai" },
    { cityName: "Lâm Đồng", districtName:"Đà Lạt" },
    { cityName: "Lâm Đồng", districtName:"Đạ Tẻh" },
    { cityName: "Lâm Đồng", districtName:"Đam Rông" },
    { cityName: "Lâm Đồng", districtName:"Di Linh" },
    { cityName: "Lâm Đồng", districtName:"Đơn Dương" },
    { cityName: "Lâm Đồng", districtName:"Đức Trọng" },
    { cityName: "Lâm Đồng", districtName:"Lạc Dương" },
    { cityName: "Lâm Đồng", districtName:"Lâm Hà" },
    { cityName: "Lạng Sơn", districtName:"Bắc Sơn" },
    { cityName: "Lạng Sơn", districtName:"Bình Gia" },
    { cityName: "Lạng Sơn", districtName:"Cao Lộc" },
    { cityName: "Lạng Sơn", districtName:"Chi Lăng" },
    { cityName: "Lạng Sơn", districtName:"Đình Lập" },
    { cityName: "Lạng Sơn", districtName:"Hữu Lũng" },
    { cityName: "Lạng Sơn", districtName:"Lạng Sơn" },
    { cityName: "Lạng Sơn", districtName:"Lộc Bình" },
    { cityName: "Lạng Sơn", districtName:"Tràng Định" },
    { cityName: "Lạng Sơn", districtName:"Văn Lãng" },
    { cityName: "Lạng Sơn", districtName:"Văn Quan" },
    { cityName: "Lào Cai", districtName:"Bắc Hà" },
    { cityName: "Lào Cai", districtName:"Bảo Thắng" },
    { cityName: "Lào Cai", districtName:"Bảo Yên" },
    { cityName: "Lào Cai", districtName:"Bát Xát" },
    { cityName: "Lào Cai", districtName:"Lào Cai" },
    { cityName: "Lào Cai", districtName:"Mường Khương" },
    { cityName: "Lào Cai", districtName:"Sa Pa" },
    { cityName: "Lào Cai", districtName:"Si Ma Cai" },
    { cityName: "Lào Cai", districtName:"Văn Bàn" },
    { cityName: "Long An", districtName:"Bến Lức" },
    { cityName: "Long An", districtName:"Cần Đước" },
    { cityName: "Long An", districtName:"Cần Giuộc" },
    { cityName: "Long An", districtName:"Châu Thành" },
    { cityName: "Long An", districtName:"Đức Hòa" },
    { cityName: "Long An", districtName:"Đức Huệ" },
    { cityName: "Long An", districtName:"Kiến Tường" },
    { cityName: "Long An", districtName:"Mộc Hóa" },
    { cityName: "Long An", districtName:"Tân An" },
    { cityName: "Long An", districtName:"Tân Hưng" },
    { cityName: "Long An", districtName:"Tân Thạnh" },
    { cityName: "Long An", districtName:"Tân Trụ" },
    { cityName: "Long An", districtName:"Thạnh Hóa" },
    { cityName: "Long An", districtName:"Thủ Thừa" },
    { cityName: "Long An", districtName:"Vĩnh Hưng" },
    { cityName: "Nam Định", districtName:"Giao Thủy" },
    { cityName: "Nam Định", districtName:"Hải Hậu" },
    { cityName: "Nam Định", districtName:"Mỹ Lộc" },
    { cityName: "Nam Định", districtName:"Nam Định" },
    { cityName: "Nam Định", districtName:"Nam Trực" },
    { cityName: "Nam Định", districtName:"Nghĩa Hưng" },
    { cityName: "Nam Định", districtName:"Trực Ninh" },
    { cityName: "Nam Định", districtName:"Vụ Bản" },
    { cityName: "Nam Định", districtName:"Xuân Trường" },
    { cityName: "Nam Định", districtName:"ý Yên" },
    { cityName: "Nghệ An", districtName:"Anh Sơn" },
    { cityName: "Nghệ An", districtName:"Con Cuông" },
    { cityName: "Nghệ An", districtName:"Cửa Lò" },
    { cityName: "Nghệ An", districtName:"Diễn Châu" },
    { cityName: "Nghệ An", districtName:"Đô Lương" },
    { cityName: "Nghệ An", districtName:"Hoàng Mai" },
    { cityName: "Nghệ An", districtName:"Hưng Nguyên" },
    { cityName: "Nghệ An", districtName:"Kỳ Sơn" },
    { cityName: "Nghệ An", districtName:"Nam Đàn" },
    { cityName: "Nghệ An", districtName:"Nghi Lộc" },
    { cityName: "Nghệ An", districtName:"Nghĩa Đàn" },
    { cityName: "Nghệ An", districtName:"Quế Phong" },
    { cityName: "Nghệ An", districtName:"Quỳ Châu" },
    { cityName: "Nghệ An", districtName:"Quỳ Hợp" },
    { cityName: "Nghệ An", districtName:"Quỳnh Lưu" },
    { cityName: "Nghệ An", districtName:"Tân Kỳ" },
    { cityName: "Nghệ An", districtName:"Thái Hòa" },
    { cityName: "Nghệ An", districtName:"Thanh Chương" },
    { cityName: "Nghệ An", districtName:"Tương Dương" },
    { cityName: "Nghệ An", districtName:"Vinh" },
    { cityName: "Nghệ An", districtName:"Yên Thành" },
    { cityName: "Ninh Bình", districtName:"Gia Viễn" },
    { cityName: "Ninh Bình", districtName:"Hoa Lư" },
    { cityName: "Ninh Bình", districtName:"Kim Sơn" },
    { cityName: "Ninh Bình", districtName:"Nho Quan" },
    { cityName: "Ninh Bình", districtName:"Ninh Bình" },
    { cityName: "Ninh Bình", districtName:"Tam Điệp" },
    { cityName: "Ninh Bình", districtName:"Yên Khánh" },
    { cityName: "Ninh Bình", districtName:"Yên Mô" },
    { cityName: "Ninh Thuận", districtName:"Bác Ái" },
    { cityName: "Ninh Thuận", districtName:"Ninh Hải" },
    { cityName: "Ninh Thuận", districtName:"Ninh Phước" },
    { cityName: "Ninh Thuận", districtName:"Ninh Sơn" },
    { cityName: "Ninh Thuận", districtName:"Phan Rang -" },
    { cityName: "Ninh Thuận", districtName:"Tháp Chàm" },
    { cityName: "Ninh Thuận", districtName:"Thuận Bắc" },
    { cityName: "Ninh Thuận", districtName:"Thuận Nam" },
    { cityName: "Phú Thọ", districtName:"Cẩm Khê" },
    { cityName: "Phú Thọ", districtName:"Đoan Hùng" },
    { cityName: "Phú Thọ", districtName:"Hạ Hòa" },
    { cityName: "Phú Thọ", districtName:"Lâm Thao" },
    { cityName: "Phú Thọ", districtName:"Phù Ninh" },
    { cityName: "Phú Thọ", districtName:"Phú Thọ" },
    { cityName: "Phú Thọ", districtName:"Tam Nông" },
    { cityName: "Phú Thọ", districtName:"Tân Sơn" },
    { cityName: "Phú Thọ", districtName:"Thanh Ba" },
    { cityName: "Phú Thọ", districtName:"Thanh Sơn" },
    { cityName: "Phú Thọ", districtName:"Thanh Thủy" },
    { cityName: "Phú Thọ", districtName:"Việt Trì" },
    { cityName: "Phú Thọ", districtName:"Yên Lập" },
    { cityName: "Phú Yên", districtName:"Đông Hòa" },
    { cityName: "Phú Yên", districtName:"Đồng Xuân" },
    { cityName: "Phú Yên", districtName:"Phú Hòa" },
    { cityName: "Phú Yên", districtName:"Sơn Hòa" },
    { cityName: "Phú Yên", districtName:"Sông Cầu" },
    { cityName: "Phú Yên", districtName:"Sông Hinh" },
    { cityName: "Phú Yên", districtName:"Tây Hòa" },
    { cityName: "Phú Yên", districtName:"Tuy An" },
    { cityName: "Phú Yên", districtName:"Tuy Hòa" },
    { cityName: "Quảng Bình", districtName:"Ba Đồn" },
    { cityName: "Quảng Bình", districtName:"Bố Trạch" },
    { cityName: "Quảng Bình", districtName:"Đồng Hới" },
    { cityName: "Quảng Bình", districtName:"Lệ Thủy" },
    { cityName: "Quảng Bình", districtName:"Minh Hóa" },
    { cityName: "Quảng Bình", districtName:"Quảng Ninh" },
    { cityName: "Quảng Bình", districtName:"Quảng Trạch" },
    { cityName: "Quảng Bình", districtName:"Tuyên Hóa" },
    { cityName: "Quảng Nam", districtName:"Bắc Trà My" },
    { cityName: "Quảng Nam", districtName:"Đại Lộc" },
    { cityName: "Quảng Nam", districtName:"Điện Bàn" },
    { cityName: "Quảng Nam", districtName:"Đông Giang" },
    { cityName: "Quảng Nam", districtName:"Duy Xuyên" },
    { cityName: "Quảng Nam", districtName:"Hiệp Đức" },
    { cityName: "Quảng Nam", districtName:"Hội An" },
    { cityName: "Quảng Nam", districtName:"Nam Giang" },
    { cityName: "Quảng Nam", districtName:"Nam Trà My" },
    { cityName: "Quảng Nam", districtName:"Nông Sơn" },
    { cityName: "Quảng Nam", districtName:"Núi Thành" },
    { cityName: "Quảng Nam", districtName:"Phú Ninh" },
    { cityName: "Quảng Nam", districtName:"Phước Sơn" },
    { cityName: "Quảng Nam", districtName:"Quế Sơn" },
    { cityName: "Quảng Nam", districtName:"Tam Kỳ" },
    { cityName: "Quảng Nam", districtName:"Tây Giang" },
    { cityName: "Quảng Nam", districtName:"Thăng Bình" },
    { cityName: "Quảng Nam", districtName:"Tiên Phước" },
    { cityName: "Quảng Ngãi", districtName:"Ba Tơ" },
    { cityName: "Quảng Ngãi", districtName:"Bình Sơn" },
    { cityName: "Quảng Ngãi", districtName:"Đức Phổ" },
    { cityName: "Quảng Ngãi", districtName:"Lý Sơn" },
    { cityName: "Quảng Ngãi", districtName:"Minh Long" },
    { cityName: "Quảng Ngãi", districtName:"Mộ Đức" },
    { cityName: "Quảng Ngãi", districtName:"Nghĩa Hành" },
    { cityName: "Quảng Ngãi", districtName:"Quảng Ngãi" },
    { cityName: "Quảng Ngãi", districtName:"Sơn Hà" },
    { cityName: "Quảng Ngãi", districtName:"Sơn Tây" },
    { cityName: "Quảng Ngãi", districtName:"Sơn Tịnh" },
    { cityName: "Quảng Ngãi", districtName:"Tây Trà" },
    { cityName: "Quảng Ngãi", districtName:"Trà Bồng" },
    { cityName: "Quảng Ngãi", districtName:"Tư Nghĩa" },
    { cityName: "Quảng Ninh", districtName:"Ba Chẽ" },
    { cityName: "Quảng Ninh", districtName:"Bình Liêu" },
    { cityName: "Quảng Ninh", districtName:"Cẩm Phả" },
    { cityName: "Quảng Ninh", districtName:"Cô Tô" },
    { cityName: "Quảng Ninh", districtName:"Đầm Hà" },
    { cityName: "Quảng Ninh", districtName:"Đông Triều" },
    { cityName: "Quảng Ninh", districtName:"Hạ Long" },
    { cityName: "Quảng Ninh", districtName:"Hải Hà" },
    { cityName: "Quảng Ninh", districtName:"Hoành Bồ" },
    { cityName: "Quảng Ninh", districtName:"Móng Cái" },
    { cityName: "Quảng Ninh", districtName:"Quảng Yên" },
    { cityName: "Quảng Ninh", districtName:"Tiên Yên" },
    { cityName: "Quảng Ninh", districtName:"Uông Bí" },
    { cityName: "Quảng Ninh", districtName:"Vân Đồn" },
    { cityName: "Quảng Trị", districtName:"Cam Lộ" },
    { cityName: "Quảng Trị", districtName:"Đakrông" },
    { cityName: "Quảng Trị", districtName:"Đảo Cồn Cỏ" },
    { cityName: "Quảng Trị", districtName:"Đông Hà" },
    { cityName: "Quảng Trị", districtName:"Gio Linh" },
    { cityName: "Quảng Trị", districtName:"Hải Lăng" },
    { cityName: "Quảng Trị", districtName:"Hướng Hóa" },
    { cityName: "Quảng Trị", districtName:"Quảng Trị" },
    { cityName: "Quảng Trị", districtName:"Triệu Phong" },
    { cityName: "Quảng Trị", districtName:"Vĩnh Linh" },
    { cityName: "Sóc Trăng", districtName:"Châu Thành" },
    { cityName: "Sóc Trăng", districtName:"Cù Lao Dung" },
    { cityName: "Sóc Trăng", districtName:"Kế Sách" },
    { cityName: "Sóc Trăng", districtName:"Long Phú" },
    { cityName: "Sóc Trăng", districtName:"Mỹ Tú" },
    { cityName: "Sóc Trăng", districtName:"Mỹ Xuyên" },
    { cityName: "Sóc Trăng", districtName:"Ngã Năm" },
    { cityName: "Sóc Trăng", districtName:"Sóc Trăng" },
    { cityName: "Sóc Trăng", districtName:"Thạnh Trị" },
    { cityName: "Sóc Trăng", districtName:"Trần Đề" },
    { cityName: "Sóc Trăng", districtName:"Vĩnh Châu" },
    { cityName: "Sơn La", districtName:"Bắc Yên" },
    { cityName: "Sơn La", districtName:"Mai Sơn" },
    { cityName: "Sơn La", districtName:"Mộc Châu" },
    { cityName: "Sơn La", districtName:"Mường La" },
    { cityName: "Sơn La", districtName:"Phù Yên" },
    { cityName: "Sơn La", districtName:"Quỳnh Nhai" },
    { cityName: "Sơn La", districtName:"Sơn La" },
    { cityName: "Sơn La", districtName:"Sông Mã" },
    { cityName: "Sơn La", districtName:"Sốp Cộp" },
    { cityName: "Sơn La", districtName:"Thuận Châu" },
    { cityName: "Sơn La", districtName:"Vân Hồ" },
    { cityName: "Sơn La", districtName:"Yên Châu" },
    { cityName: "Tây Ninh", districtName:"Bến Cầu" },
    { cityName: "Tây Ninh", districtName:"Châu Thành" },
    { cityName: "Tây Ninh", districtName:"Dương Minh Châu" },
    { cityName: "Tây Ninh", districtName:"Gò Dầu" },
    { cityName: "Tây Ninh", districtName:"Hòa Thành" },
    { cityName: "Tây Ninh", districtName:"Tân Biên" },
    { cityName: "Tây Ninh", districtName:"Tân Châu" },
    { cityName: "Tây Ninh", districtName:"Tây Ninh" },
    { cityName: "Tây Ninh", districtName:"Trảng Bàng" },
    { cityName: "Thái Bình", districtName:"Đông Hưng" },
    { cityName: "Thái Bình", districtName:"Hưng Hà" },
    { cityName: "Thái Bình", districtName:"Kiến Xương" },
    { cityName: "Thái Bình", districtName:"Quỳnh Phụ" },
    { cityName: "Thái Bình", districtName:"Thái Bình" },
    { cityName: "Thái Bình", districtName:"Thái Thụy" },
    { cityName: "Thái Bình", districtName:"Tiền Hải" },
    { cityName: "Thái Bình", districtName:"Vũ Thư" },
    { cityName: "Thái Nguyên", districtName:"Đại Từ" },
    { cityName: "Thái Nguyên", districtName:"Định Hóa" },
    { cityName: "Thái Nguyên", districtName:"Đồng Hỷ" },
    { cityName: "Thái Nguyên", districtName:"Phổ Yên" },
    { cityName: "Thái Nguyên", districtName:"Phú Bình" },
    { cityName: "Thái Nguyên", districtName:"Phú Lương" },
    { cityName: "Thái Nguyên", districtName:"Sông Công" },
    { cityName: "Thái Nguyên", districtName:"Thái Nguyên" },
    { cityName: "Thái Nguyên", districtName:"Võ Nhai" },
    { cityName: "Thanh Hóa", districtName:"Bá Thước" },
    { cityName: "Thanh Hóa", districtName:"Bỉm Sơn" },
    { cityName: "Thanh Hóa", districtName:"Cẩm Thủy" },
    { cityName: "Thanh Hóa", districtName:"Đông Sơn" },
    { cityName: "Thanh Hóa", districtName:"Hà Trung" },
    { cityName: "Thanh Hóa", districtName:"Hậu Lộc" },
    { cityName: "Thanh Hóa", districtName:"Hoằng Hóa" },
    { cityName: "Thanh Hóa", districtName:"Lang Chánh" },
    { cityName: "Thanh Hóa", districtName:"Mường Lát" },
    { cityName: "Thanh Hóa", districtName:"Nga Sơn" },
    { cityName: "Thanh Hóa", districtName:"Ngọc Lặc" },
    { cityName: "Thanh Hóa", districtName:"Như Thanh" },
    { cityName: "Thanh Hóa", districtName:"Như Xuân" },
    { cityName: "Thanh Hóa", districtName:"Nông Cống" },
    { cityName: "Thanh Hóa", districtName:"Quan Hóa" },
    { cityName: "Thanh Hóa", districtName:"Quan Sơn" },
    { cityName: "Thanh Hóa", districtName:"Quảng Xương" },
    { cityName: "Thanh Hóa", districtName:"Sầm Sơn" },
    { cityName: "Thanh Hóa", districtName:"Thạch Thành" },
    { cityName: "Thanh Hóa", districtName:"Thanh Hóa" },
    { cityName: "Thanh Hóa", districtName:"Thiệu Hóa" },
    { cityName: "Thanh Hóa", districtName:"Thọ Xuân" },
    { cityName: "Thanh Hóa", districtName:"Thường Xuân" },
    { cityName: "Thanh Hóa", districtName:"Tĩnh Gia" },
    { cityName: "Thanh Hóa", districtName:"Triệu Sơn" },
    { cityName: "Thanh Hóa", districtName:"Vĩnh Lộc" },
    { cityName: "Thanh Hóa", districtName:"Yên Định" },
    { cityName: "Thừa Thiên Huế", districtName:"A Lưới" },
    { cityName: "Thừa Thiên Huế", districtName:"Huế" },
    { cityName: "Thừa Thiên Huế", districtName:"Hương Thủy" },
    { cityName: "Thừa Thiên Huế", districtName:"Hương Trà" },
    { cityName: "Thừa Thiên Huế", districtName:"Nam Đông" },
    { cityName: "Thừa Thiên Huế", districtName:"Phong Điền" },
    { cityName: "Thừa Thiên Huế", districtName:"Phú Lộc" },
    { cityName: "Thừa Thiên Huế", districtName:"Phú Vang" },
    { cityName: "Thừa Thiên Huế", districtName:"Quảng Điền" },
    { cityName: "Tiền Giang", districtName:"Cái Bè" },
    { cityName: "Tiền Giang", districtName:"Cai Lậy" },
    { cityName: "Tiền Giang", districtName:"Cai Lậy" },
    { cityName: "Tiền Giang", districtName:"Châu Thành" },
    { cityName: "Tiền Giang", districtName:"Chợ Gạo" },
    { cityName: "Tiền Giang", districtName:"Gò Công" },
    { cityName: "Tiền Giang", districtName:"Gò Công Đông" },
    { cityName: "Tiền Giang", districtName:"Gò Công Tây" },
    { cityName: "Tiền Giang", districtName:"Mỹ Tho" },
    { cityName: "Tiền Giang", districtName:"Tân Phú Đông" },
    { cityName: "Tiền Giang", districtName:"Tân Phước" },
    { cityName: "Trà Vinh", districtName:"Càng Long" },
    { cityName: "Trà Vinh", districtName:"Cầu Kè" },
    { cityName: "Trà Vinh", districtName:"Cầu Ngang" },
    { cityName: "Trà Vinh", districtName:"Châu Thành" },
    { cityName: "Trà Vinh", districtName:"Duyên Hải" },
    { cityName: "Trà Vinh", districtName:"Duyên Hải" },
    { cityName: "Trà Vinh", districtName:"Tiểu Cần" },
    { cityName: "Trà Vinh", districtName:"Trà Cú" },
    { cityName: "Trà Vinh", districtName:"Trà Vinh" },
    { cityName: "Tuyên Quang", districtName:"Chiêm Hóa" },
    { cityName: "Tuyên Quang", districtName:"Hàm Yên" },
    { cityName: "Tuyên Quang", districtName:"Lâm Bình" },
    { cityName: "Tuyên Quang", districtName:"Na Hang" },
    { cityName: "Tuyên Quang", districtName:"Sơn Dương" },
    { cityName: "Tuyên Quang", districtName:"Tuyên Quang" },
    { cityName: "Tuyên Quang", districtName:"Yên Sơn" },
    { cityName: "Vĩnh Long", districtName:"Bình Minh" },
    { cityName: "Vĩnh Long", districtName:"Bình Tân" },
    { cityName: "Vĩnh Long", districtName:"Long Hồ" },
    { cityName: "Vĩnh Long", districtName:"Mang Thít" },
    { cityName: "Vĩnh Long", districtName:"Tam Bình" },
    { cityName: "Vĩnh Long", districtName:"Trà Ôn" },
    { cityName: "Vĩnh Long", districtName:"Vĩnh Long" },
    { cityName: "Vĩnh Long", districtName:"Vũng Liêm" },
    { cityName: "Vĩnh Phúc", districtName:"Bình Xuyên" },
    { cityName: "Vĩnh Phúc", districtName:"Lập Thạch" },
    { cityName: "Vĩnh Phúc", districtName:"Phúc Yên" },
    { cityName: "Vĩnh Phúc", districtName:"Sông Lô" },
    { cityName: "Vĩnh Phúc", districtName:"Tam Đảo" },
    { cityName: "Vĩnh Phúc", districtName:"Tam Dương" },
    { cityName: "Vĩnh Phúc", districtName:"Vĩnh Tường" },
    { cityName: "Vĩnh Phúc", districtName:"Vĩnh Yên" },
    { cityName: "Vĩnh Phúc", districtName:"Yên Lạc" },
    { cityName: "Yên Bái", districtName:"Lục Yên" },
    { cityName: "Yên Bái", districtName:"Mù Cang Chải" },
    { cityName: "Yên Bái", districtName:"Nghĩa Lộ" },
    { cityName: "Yên Bái", districtName:"Trạm Tấu" },
    { cityName: "Yên Bái", districtName:"Trấn Yên" },
    { cityName: "Yên Bái", districtName:"Văn Chấn" },
    { cityName: "Yên Bái", districtName:"Văn Yên" },
    { cityName: "Yên Bái", districtName:"Yên Bái" },
    { cityName: "Yên Bái", districtName:"Yên Bình" }
];

module.exports.createDefaultCollection = async () => {
    const districtsArray = await DistrictDao.find();
    if (districtsArray.length <= 0) {
        console.log("District collection is empty.");
        const cities = await CityDao.find();
        if (cities.length <= 0) {
            console.log("City collection is empty.");
        } else {
            cities.map(city => {
                districts.map(district => {
                    if (city.name.localeCompare(district.cityName) == 0) {
                        const newDistrict = new District({
                            name: district.districtName,
                            city: city
                        });
                        DistrictDao.save(newDistrict);
                    }
                });
            });
            console.log("Default District collection created.");
        }
    } else {
        console.log("District collection existed.");
    }
};
