var md5 = require('md5');

const User = require("../../models/user.model");
const UserDao = require("../../dao/user.dao");
const AuthorizationDao = require("../../dao/authorization.dao");

// console.log(md5("e10adc3949ba59abbe56e057f20f883e")); //e10adc3949ba59abbe56e057f20f883e

const users = [
    {authorizationName: "Admin", fullname: { firstname: "Admin5", lastname: "Admin" }, phone: "123456793", email: "admin5@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "Employee", fullname: { firstname: "Employee1", lastname: "Employee" }, phone: "123456794", email: "employee1@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "Employee", fullname: { firstname: "Employee2", lastname: "Employee" }, phone: "123456795", email: "employee2@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "Employee", fullname: { firstname: "Employee3", lastname: "Employee" }, phone: "123456796", email: "employee3@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "Employee", fullname: { firstname: "Employee4", lastname: "Employee" }, phone: "123456797", email: "employee4@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "Employee", fullname: { firstname: "Employee5", lastname: "Employee" }, phone: "123456798", email: "employee5@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User1", lastname: "User" }, phone: "123456799", email: "user1@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User2", lastname: "User" }, phone: "123456800", email: "user2@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User3", lastname: "User" }, phone: "123456801", email: "user3@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User4", lastname: "User" }, phone: "123456802", email: "user4@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User5", lastname: "User" }, phone: "123456803", email: "user5@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User6", lastname: "User" }, phone: "123456804", email: "user6@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User7", lastname: "User" }, phone: "123456805", email: "user7@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User8", lastname: "User" }, phone: "123456806", email: "user8@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User9", lastname: "User" }, phone: "123456807", email: "user9@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User10", lastname: "User" }, phone: "123456808", email: "user10@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User11", lastname: "User" }, phone: "123456809", email: "user11@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User12", lastname: "User" }, phone: "123456810", email: "user12@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User13", lastname: "User" }, phone: "123456811", email: "user13@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User14", lastname: "User" }, phone: "123456812", email: "user14@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User15", lastname: "User" }, phone: "123456813", email: "user15@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User16", lastname: "User" }, phone: "123456814", email: "user16@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User17", lastname: "User" }, phone: "123456815", email: "user17@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User18", lastname: "User" }, phone: "123456816", email: "user18@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User19", lastname: "User" }, phone: "123456817", email: "user19@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User20", lastname: "User" }, phone: "123456818", email: "user20@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User21", lastname: "User" }, phone: "123456819", email: "user21@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User22", lastname: "User" }, phone: "123456820", email: "user22@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User23", lastname: "User" }, phone: "123456821", email: "user23@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User24", lastname: "User" }, phone: "123456822", email: "user24@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User25", lastname: "User" }, phone: "123456823", email: "user25@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User26", lastname: "User" }, phone: "123456824", email: "user26@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User27", lastname: "User" }, phone: "123456825", email: "user27@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User28", lastname: "User" }, phone: "123456826", email: "user28@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User29", lastname: "User" }, phone: "123456827", email: "user29@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User30", lastname: "User" }, phone: "123456828", email: "user30@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User31", lastname: "User" }, phone: "123456829", email: "user31@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User32", lastname: "User" }, phone: "123456830", email: "user32@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User33", lastname: "User" }, phone: "123456831", email: "user33@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User34", lastname: "User" }, phone: "123456832", email: "user34@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User35", lastname: "User" }, phone: "123456833", email: "user35@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User36", lastname: "User" }, phone: "123456834", email: "user36@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User37", lastname: "User" }, phone: "123456835", email: "user37@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User38", lastname: "User" }, phone: "123456836", email: "user38@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User39", lastname: "User" }, phone: "123456837", email: "user39@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User40", lastname: "User" }, phone: "123456838", email: "user40@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User41", lastname: "User" }, phone: "123456839", email: "user41@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User42", lastname: "User" }, phone: "123456840", email: "user42@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User43", lastname: "User" }, phone: "123456841", email: "user43@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User44", lastname: "User" }, phone: "123456842", email: "user44@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User45", lastname: "User" }, phone: "123456843", email: "user45@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User46", lastname: "User" }, phone: "123456844", email: "user46@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User47", lastname: "User" }, phone: "123456845", email: "user47@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User48", lastname: "User" }, phone: "123456846", email: "user48@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User49", lastname: "User" }, phone: "123456847", email: "user49@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User50", lastname: "User" }, phone: "123456848", email: "user50@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User51", lastname: "User" }, phone: "123456849", email: "user51@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User52", lastname: "User" }, phone: "123456850", email: "user52@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User53", lastname: "User" }, phone: "123456851", email: "user53@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User54", lastname: "User" }, phone: "123456852", email: "user54@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User55", lastname: "User" }, phone: "123456853", email: "user55@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User56", lastname: "User" }, phone: "123456854", email: "user56@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User57", lastname: "User" }, phone: "123456855", email: "user57@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User58", lastname: "User" }, phone: "123456856", email: "user58@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User59", lastname: "User" }, phone: "123456857", email: "user59@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User60", lastname: "User" }, phone: "123456858", email: "user60@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User61", lastname: "User" }, phone: "123456859", email: "user61@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User62", lastname: "User" }, phone: "123456860", email: "user62@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User63", lastname: "User" }, phone: "123456861", email: "user63@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User64", lastname: "User" }, phone: "123456862", email: "user64@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User65", lastname: "User" }, phone: "123456863", email: "user65@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User66", lastname: "User" }, phone: "123456864", email: "user66@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User67", lastname: "User" }, phone: "123456865", email: "user67@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User68", lastname: "User" }, phone: "123456866", email: "user68@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User69", lastname: "User" }, phone: "123456867", email: "user69@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User70", lastname: "User" }, phone: "123456868", email: "user70@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User71", lastname: "User" }, phone: "123456869", email: "user71@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User72", lastname: "User" }, phone: "123456870", email: "user72@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User73", lastname: "User" }, phone: "123456871", email: "user73@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User74", lastname: "User" }, phone: "123456872", email: "user74@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User75", lastname: "User" }, phone: "123456873", email: "user75@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User76", lastname: "User" }, phone: "123456874", email: "user76@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User77", lastname: "User" }, phone: "123456875", email: "user77@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User78", lastname: "User" }, phone: "123456876", email: "user78@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User79", lastname: "User" }, phone: "123456877", email: "user79@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User80", lastname: "User" }, phone: "123456878", email: "user80@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User81", lastname: "User" }, phone: "123456879", email: "user81@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User82", lastname: "User" }, phone: "123456880", email: "user82@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User83", lastname: "User" }, phone: "123456881", email: "user83@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User84", lastname: "User" }, phone: "123456882", email: "user84@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User85", lastname: "User" }, phone: "123456883", email: "user85@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User86", lastname: "User" }, phone: "123456884", email: "user86@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User87", lastname: "User" }, phone: "123456885", email: "user87@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User88", lastname: "User" }, phone: "123456886", email: "user88@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User89", lastname: "User" }, phone: "123456887", email: "user89@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User90", lastname: "User" }, phone: "123456888", email: "user90@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User91", lastname: "User" }, phone: "123456889", email: "user91@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User92", lastname: "User" }, phone: "123456890", email: "user92@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User93", lastname: "User" }, phone: "123456891", email: "user93@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User94", lastname: "User" }, phone: "123456892", email: "user94@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User95", lastname: "User" }, phone: "123456893", email: "user95@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User96", lastname: "User" }, phone: "123456894", email: "user96@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User97", lastname: "User" }, phone: "123456895", email: "user97@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User98", lastname: "User" }, phone: "123456896", email: "user98@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User99", lastname: "User" }, phone: "123456897", email: "user99@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]},
    {authorizationName: "User", fullname: { firstname: "User100", lastname: "User" }, phone: "123456898", email: "user100@gmail.com", password: "123456", address: "Thủ Đức, Hồ Chí Minh", gender: false, birthday: "1999-06-18", timeRegister: Date.now(), avatars: ["images/nancy_avatar.jpg"]}
];

module.exports.createDefaultCollection = async () => {
    const usersArray = await UserDao.find();
    if(usersArray.length <= 0){
        console.log("User collection is empty.");
        const authorizations = await AuthorizationDao.find();
        if(authorizations.length <= 0){
            console.log("Authorization collection is empty.");
        }
        else{            
            authorizations.map(authorization => {
                users.map(user => {
                    if (user.authorizationName.localeCompare(authorization.name) == 0) {
                        const userNew = new User({
                            authorization: authorization,
                            fullname: user.fullname,
                            phone: user.phone,
                            email: user.email,
                            password: user.password,
                            address: user.address,
                            gender: user.gender,
                            birthday: user.birthday,
                            timeRegister: user.timeRegister,
                            avatars: user.avatars
                        });    
                        UserDao.save(userNew);
                    }
                });
            });
            console.log("Default User collection created.");   
        }   
    }
    else{
        console.log("User collection existed.");
    }
};
