package com.huupham.entities;
// Generated Oct 13, 2019, 8:16:52 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Authorization generated by hbm2java
 */
@Entity
@Table(name = "authorization", catalog = "db247hostel")
public class Authorization implements java.io.Serializable {

	private int id;
	private String name;
	private Set<User> users = new HashSet<User>(0);

	public Authorization() {
	}

	public Authorization(int id) {
		this.id = id;
	}

	public Authorization(int id, String name, Set<User> users) {
		this.id = id;
		this.name = name;
		this.users = users;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authorization")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
