package com.huupham.entities;
// Generated Oct 20, 2019 3:14:09 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "db247hostel")
public class City implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<District> districts = new HashSet<District>(0);
	private Set<Hostel> hostels = new HashSet<Hostel>(0);

	public City() {
	}

	public City(String name) {
		this.name = name;
	}

	public City(String name, Set<District> districts, Set<Hostel> hostels) {
		this.name = name;
		this.districts = districts;
		this.hostels = hostels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set<District> districts) {
		this.districts = districts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Hostel> getHostels() {
		return this.hostels;
	}

	public void setHostels(Set<Hostel> hostels) {
		this.hostels = hostels;
	}

}
