package com.huupham.entities;
// Generated Oct 20, 2019 3:14:09 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conversation generated by hbm2java
 */
@Entity
@Table(name = "conversation", catalog = "db247hostel")
public class Conversation implements java.io.Serializable {

	private int id;
	private User userByIdUser1;
	private User userByIdUser2;
	private Set<Message> messages = new HashSet<Message>(0);

	public Conversation() {
	}

	public Conversation(int id, User userByIdUser1, User userByIdUser2) {
		this.id = id;
		this.userByIdUser1 = userByIdUser1;
		this.userByIdUser2 = userByIdUser2;
	}

	public Conversation(int id, User userByIdUser1, User userByIdUser2, Set<Message> messages) {
		this.id = id;
		this.userByIdUser1 = userByIdUser1;
		this.userByIdUser2 = userByIdUser2;
		this.messages = messages;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser1", nullable = false)
	public User getUserByIdUser1() {
		return this.userByIdUser1;
	}

	public void setUserByIdUser1(User userByIdUser1) {
		this.userByIdUser1 = userByIdUser1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser2", nullable = false)
	public User getUserByIdUser2() {
		return this.userByIdUser2;
	}

	public void setUserByIdUser2(User userByIdUser2) {
		this.userByIdUser2 = userByIdUser2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conversation")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

}
