package com.huupham.entities;
// Generated Oct 20, 2019 3:14:09 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Hostel generated by hbm2java
 */
@Entity
@Table(name = "hostel", catalog = "db247hostel")
public class Hostel implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private City city;
	private District district;
	private Street street;
	private User user;
	private String hostelNumber;
	private int price;
	private int space;
	private String title;
	private String description;
	private boolean isRented;
	private int isCensored;
	private Float locationLat;
	private Float locationLng;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Image> images = new HashSet<Image>(0);
	private Set<Rate> rates = new HashSet<Rate>(0);
	private Set<Video> videos = new HashSet<Video>(0);
	private Set<VipHostel> vipHostels = new HashSet<VipHostel>(0);

	public Hostel() {
	}

	public Hostel(City city, District district, Street street, User user, String hostelNumber, int price, int space,
			String title, String description, boolean isRented, int isCensored) {
		this.city = city;
		this.district = district;
		this.street = street;
		this.user = user;
		this.hostelNumber = hostelNumber;
		this.price = price;
		this.space = space;
		this.title = title;
		this.description = description;
		this.isRented = isRented;
		this.isCensored = isCensored;
	}

	public Hostel(City city, District district, Street street, User user, String hostelNumber, int price, int space,
			String title, String description, boolean isRented, int isCensored, Float locationLat, Float locationLng,
			Set<Comment> comments, Set<Image> images, Set<Rate> rates, Set<Video> videos, Set<VipHostel> vipHostels) {
		this.city = city;
		this.district = district;
		this.street = street;
		this.user = user;
		this.hostelNumber = hostelNumber;
		this.price = price;
		this.space = space;
		this.title = title;
		this.description = description;
		this.isRented = isRented;
		this.isCensored = isCensored;
		this.locationLat = locationLat;
		this.locationLng = locationLng;
		this.comments = comments;
		this.images = images;
		this.rates = rates;
		this.videos = videos;
		this.vipHostels = vipHostels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 19)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCity", nullable = false)
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDistrict", nullable = false)
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idStreet", nullable = false)
	public Street getStreet() {
		return this.street;
	}

	public void setStreet(Street street) {
		this.street = street;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "hostelNumber", nullable = false, length = 10)
	public String getHostelNumber() {
		return this.hostelNumber;
	}

	public void setHostelNumber(String hostelNumber) {
		this.hostelNumber = hostelNumber;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "space", nullable = false)
	public int getSpace() {
		return this.space;
	}

	public void setSpace(int space) {
		this.space = space;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", nullable = false, length = 2500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "isRented", nullable = false)
	public boolean isIsRented() {
		return this.isRented;
	}

	public void setIsRented(boolean isRented) {
		this.isRented = isRented;
	}

	@Column(name = "isCensored", nullable = false)
	public int getIsCensored() {
		return this.isCensored;
	}

	public void setIsCensored(int isCensored) {
		this.isCensored = isCensored;
	}

	@Column(name = "locationLat", precision = 12, scale = 0)
	public Float getLocationLat() {
		return this.locationLat;
	}

	public void setLocationLat(Float locationLat) {
		this.locationLat = locationLat;
	}

	@Column(name = "locationLng", precision = 12, scale = 0)
	public Float getLocationLng() {
		return this.locationLng;
	}

	public void setLocationLng(Float locationLng) {
		this.locationLng = locationLng;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hostel")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hostel")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hostel")
	public Set<Rate> getRates() {
		return this.rates;
	}

	public void setRates(Set<Rate> rates) {
		this.rates = rates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hostel")
	public Set<Video> getVideos() {
		return this.videos;
	}

	public void setVideos(Set<Video> videos) {
		this.videos = videos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hostel")
	public Set<VipHostel> getVipHostels() {
		return this.vipHostels;
	}

	public void setVipHostels(Set<VipHostel> vipHostels) {
		this.vipHostels = vipHostels;
	}

}
